spring:
  application:
    name: SecurityPractice

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test1!
    url: jdbc:mariadb://localhost:3306/public

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    open-in-view: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.example.Security.Service.CustomUserDetailsService: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET}
